### ISSUE TITLE
Bad pursuit point at begining

### ISSUE THREAD

**Issue by alvarolp02** [ARUSfs/DRIVERLESS2#91]
When starting the simulation the pursuit point is at origin and the vehicle turns right. Fix it so that the controller doesn't command torque until the trajectory is ok

**Comment by francisrojass** [comment]
This problem is generate because the car start a position where the position initial is more near of final trajectory that the starting, Therefore, the index_global_ in the starting is 996,997,998,..,0,1,2...
This problem can to solution with a temporal conditional, besides, this problem would not have it in real life because the car will start with a front trajectory and the second lap, the car would be running and it would close the trajectory.
